# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160418_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
