# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160419_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='message',
            new_name='start_message',
        ),
        migrations.AddField(
            model_name='log',
            name='end_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
