# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20160412_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=15)),
                ('date_started', models.DateTimeField()),
                ('shift_length', models.IntegerField(default=8)),
                ('status', models.CharField(choices=[('R', 'Regular'), ('PT', 'Part Time'), ('P', 'Probationary'), ('I', 'Intern'), ('T', 'Terminated')], max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
