# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160419_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_length', models.IntegerField()),
                ('author', models.CharField(blank=True, max_length=140, null=True)),
                ('text', models.CharField(blank=True, max_length=140, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
