# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20160427_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
